module StripeAPI.Types.AccountBusinessProfile where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data AccountBusinessProfile
instance Show AccountBusinessProfile
instance Eq AccountBusinessProfile
instance FromJSON AccountBusinessProfile
instance ToJSON AccountBusinessProfile
data AccountBusinessProfileAnnualRevenue'NonNullable
instance Show AccountBusinessProfileAnnualRevenue'NonNullable
instance Eq AccountBusinessProfileAnnualRevenue'NonNullable
instance FromJSON AccountBusinessProfileAnnualRevenue'NonNullable
instance ToJSON AccountBusinessProfileAnnualRevenue'NonNullable
data AccountBusinessProfileSupportAddress'NonNullable
instance Show AccountBusinessProfileSupportAddress'NonNullable
instance Eq AccountBusinessProfileSupportAddress'NonNullable
instance FromJSON AccountBusinessProfileSupportAddress'NonNullable
instance ToJSON AccountBusinessProfileSupportAddress'NonNullable
