-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema ConnectAccountReference
module StripeAPI.Types.ConnectAccountReference where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.Account

-- | Defines the object schema located at @components.schemas.connect_account_reference@ in the specification.
-- 
-- 
data ConnectAccountReference = ConnectAccountReference {
  -- | account: The connected account being referenced when \`type\` is \`account\`.
  connectAccountReferenceAccount :: (GHC.Maybe.Maybe ConnectAccountReferenceAccount'Variants)
  -- | type: Type of the account referenced.
  , connectAccountReferenceType :: ConnectAccountReferenceType'
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON ConnectAccountReference
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account" Data.Aeson.Types.ToJSON..=)) (connectAccountReferenceAccount obj) : ["type" Data.Aeson.Types.ToJSON..= connectAccountReferenceType obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account" Data.Aeson.Types.ToJSON..=)) (connectAccountReferenceAccount obj) : ["type" Data.Aeson.Types.ToJSON..= connectAccountReferenceType obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON ConnectAccountReference
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "ConnectAccountReference" (\obj -> (GHC.Base.pure ConnectAccountReference GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "account")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type"))}
-- | Create a new 'ConnectAccountReference' with all required fields.
mkConnectAccountReference :: ConnectAccountReferenceType' -- ^ 'connectAccountReferenceType'
  -> ConnectAccountReference
mkConnectAccountReference connectAccountReferenceType = ConnectAccountReference{connectAccountReferenceAccount = GHC.Maybe.Nothing,
                                                                                connectAccountReferenceType = connectAccountReferenceType}
-- | Defines the oneOf schema located at @components.schemas.connect_account_reference.properties.account.anyOf@ in the specification.
-- 
-- The connected account being referenced when \`type\` is \`account\`.
data ConnectAccountReferenceAccount'Variants =
   ConnectAccountReferenceAccount'Text Data.Text.Internal.Text
  | ConnectAccountReferenceAccount'Account Account
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON ConnectAccountReferenceAccount'Variants
    where {toJSON (ConnectAccountReferenceAccount'Text a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (ConnectAccountReferenceAccount'Account a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON ConnectAccountReferenceAccount'Variants
    where {parseJSON val = case (ConnectAccountReferenceAccount'Text Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((ConnectAccountReferenceAccount'Account Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the enum schema located at @components.schemas.connect_account_reference.properties.type@ in the specification.
-- 
-- Type of the account referenced.
data ConnectAccountReferenceType' =
   ConnectAccountReferenceType'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | ConnectAccountReferenceType'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | ConnectAccountReferenceType'EnumAccount -- ^ Represents the JSON value @"account"@
  | ConnectAccountReferenceType'EnumSelf -- ^ Represents the JSON value @"self"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON ConnectAccountReferenceType'
    where {toJSON (ConnectAccountReferenceType'Other val) = val;
           toJSON (ConnectAccountReferenceType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (ConnectAccountReferenceType'EnumAccount) = "account";
           toJSON (ConnectAccountReferenceType'EnumSelf) = "self"}
instance Data.Aeson.Types.FromJSON.FromJSON ConnectAccountReferenceType'
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "account" -> ConnectAccountReferenceType'EnumAccount
                                             | val GHC.Classes.== "self" -> ConnectAccountReferenceType'EnumSelf
                                             | GHC.Base.otherwise -> ConnectAccountReferenceType'Other val)}
