-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema InvoiceSettingSubscriptionSchedulePhaseSetting
module StripeAPI.Types.InvoiceSettingSubscriptionSchedulePhaseSetting where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.Account
import {-# SOURCE #-} StripeAPI.Types.ConnectAccountReference

-- | Defines the object schema located at @components.schemas.invoice_setting_subscription_schedule_phase_setting@ in the specification.
-- 
-- 
data InvoiceSettingSubscriptionSchedulePhaseSetting = InvoiceSettingSubscriptionSchedulePhaseSetting {
  -- | days_until_due: Number of days within which a customer must pay invoices generated by this subscription schedule. This value will be \`null\` for subscription schedules where \`billing=charge_automatically\`.
  invoiceSettingSubscriptionSchedulePhaseSettingDaysUntilDue :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable GHC.Types.Int))
  -- | issuer: The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
  , invoiceSettingSubscriptionSchedulePhaseSettingIssuer :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON InvoiceSettingSubscriptionSchedulePhaseSetting
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("days_until_due" Data.Aeson.Types.ToJSON..=)) (invoiceSettingSubscriptionSchedulePhaseSettingDaysUntilDue obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("issuer" Data.Aeson.Types.ToJSON..=)) (invoiceSettingSubscriptionSchedulePhaseSettingIssuer obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("days_until_due" Data.Aeson.Types.ToJSON..=)) (invoiceSettingSubscriptionSchedulePhaseSettingDaysUntilDue obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("issuer" Data.Aeson.Types.ToJSON..=)) (invoiceSettingSubscriptionSchedulePhaseSettingIssuer obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON InvoiceSettingSubscriptionSchedulePhaseSetting
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "InvoiceSettingSubscriptionSchedulePhaseSetting" (\obj -> (GHC.Base.pure InvoiceSettingSubscriptionSchedulePhaseSetting GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "days_until_due")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "issuer"))}
-- | Create a new 'InvoiceSettingSubscriptionSchedulePhaseSetting' with all required fields.
mkInvoiceSettingSubscriptionSchedulePhaseSetting :: InvoiceSettingSubscriptionSchedulePhaseSetting
mkInvoiceSettingSubscriptionSchedulePhaseSetting = InvoiceSettingSubscriptionSchedulePhaseSetting{invoiceSettingSubscriptionSchedulePhaseSettingDaysUntilDue = GHC.Maybe.Nothing,
                                                                                                  invoiceSettingSubscriptionSchedulePhaseSettingIssuer = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.invoice_setting_subscription_schedule_phase_setting.properties.issuer.anyOf@ in the specification.
-- 
-- The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
data InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable = InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable {
  -- | account: The connected account being referenced when \`type\` is \`account\`.
  invoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount :: (GHC.Maybe.Maybe InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Variants)
  -- | type: Type of the account referenced.
  , invoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType :: (GHC.Maybe.Maybe InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType')
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account" Data.Aeson.Types.ToJSON..=)) (invoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (invoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account" Data.Aeson.Types.ToJSON..=)) (invoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (invoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable" (\obj -> (GHC.Base.pure InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "account")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "type"))}
-- | Create a new 'InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable' with all required fields.
mkInvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable :: InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable
mkInvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable = InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable{invoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount = GHC.Maybe.Nothing,
                                                                                                                                      invoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType = GHC.Maybe.Nothing}
-- | Defines the oneOf schema located at @components.schemas.invoice_setting_subscription_schedule_phase_setting.properties.issuer.anyOf.properties.account.anyOf@ in the specification.
-- 
-- The connected account being referenced when \`type\` is \`account\`.
data InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Variants =
   InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Text Data.Text.Internal.Text
  | InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Account Account
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Variants
    where {toJSON (InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Text a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Account a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Variants
    where {parseJSON val = case (InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Text Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Account Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the enum schema located at @components.schemas.invoice_setting_subscription_schedule_phase_setting.properties.issuer.anyOf.properties.type@ in the specification.
-- 
-- Type of the account referenced.
data InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType' =
   InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'EnumAccount -- ^ Represents the JSON value @"account"@
  | InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'EnumSelf -- ^ Represents the JSON value @"self"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'
    where {toJSON (InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'Other val) = val;
           toJSON (InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'EnumAccount) = "account";
           toJSON (InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'EnumSelf) = "self"}
instance Data.Aeson.Types.FromJSON.FromJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "account" -> InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'EnumAccount
                                             | val GHC.Classes.== "self" -> InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'EnumSelf
                                             | GHC.Base.otherwise -> InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'Other val)}
