module StripeAPI.Types.InvoiceSettingSubscriptionSchedulePhaseSetting where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoiceSettingSubscriptionSchedulePhaseSetting
instance Show InvoiceSettingSubscriptionSchedulePhaseSetting
instance Eq InvoiceSettingSubscriptionSchedulePhaseSetting
instance FromJSON InvoiceSettingSubscriptionSchedulePhaseSetting
instance ToJSON InvoiceSettingSubscriptionSchedulePhaseSetting
data InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable
instance Show InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable
instance Eq InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable
instance FromJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable
instance ToJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable
data InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Variants
instance Show InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Variants
instance Eq InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Variants
instance FromJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Variants
instance ToJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Variants
data InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'
instance Show InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'
instance Eq InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'
instance FromJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'
instance ToJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'
