-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema PaymentLinksResourceInvoiceCreation
module StripeAPI.Types.PaymentLinksResourceInvoiceCreation where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.Account
import {-# SOURCE #-} StripeAPI.Types.ConnectAccountReference
import {-# SOURCE #-} StripeAPI.Types.DeletedTaxId
import {-# SOURCE #-} StripeAPI.Types.InvoiceSettingCustomField
import {-# SOURCE #-} StripeAPI.Types.InvoiceSettingRenderingOptions
import {-# SOURCE #-} StripeAPI.Types.PaymentLinksResourceInvoiceSettings
import {-# SOURCE #-} StripeAPI.Types.TaxId

-- | Defines the object schema located at @components.schemas.payment_links_resource_invoice_creation@ in the specification.
-- 
-- 
data PaymentLinksResourceInvoiceCreation = PaymentLinksResourceInvoiceCreation {
  -- | enabled: Enable creating an invoice on successful payment.
  paymentLinksResourceInvoiceCreationEnabled :: GHC.Types.Bool
  -- | invoice_data: Configuration for the invoice. Default invoice values will be used if unspecified.
  , paymentLinksResourceInvoiceCreationInvoiceData :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentLinksResourceInvoiceCreation
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["enabled" Data.Aeson.Types.ToJSON..= paymentLinksResourceInvoiceCreationEnabled obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_data" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["enabled" Data.Aeson.Types.ToJSON..= paymentLinksResourceInvoiceCreationEnabled obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_data" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentLinksResourceInvoiceCreation
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentLinksResourceInvoiceCreation" (\obj -> (GHC.Base.pure PaymentLinksResourceInvoiceCreation GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "enabled")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "invoice_data"))}
-- | Create a new 'PaymentLinksResourceInvoiceCreation' with all required fields.
mkPaymentLinksResourceInvoiceCreation :: GHC.Types.Bool -- ^ 'paymentLinksResourceInvoiceCreationEnabled'
  -> PaymentLinksResourceInvoiceCreation
mkPaymentLinksResourceInvoiceCreation paymentLinksResourceInvoiceCreationEnabled = PaymentLinksResourceInvoiceCreation{paymentLinksResourceInvoiceCreationEnabled = paymentLinksResourceInvoiceCreationEnabled,
                                                                                                                       paymentLinksResourceInvoiceCreationInvoiceData = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.payment_links_resource_invoice_creation.properties.invoice_data.anyOf@ in the specification.
-- 
-- Configuration for the invoice. Default invoice values will be used if unspecified.
data PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable = PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable {
  -- | account_tax_ids: The account tax IDs associated with the invoice.
  paymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable ([PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableVariants])))
  -- | custom_fields: A list of up to 4 custom fields to be displayed on the invoice.
  , paymentLinksResourceInvoiceCreationInvoiceData'NonNullableCustomFields :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable ([InvoiceSettingCustomField])))
  -- | description: An arbitrary string attached to the object. Often useful for displaying to users.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , paymentLinksResourceInvoiceCreationInvoiceData'NonNullableDescription :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text))
  -- | footer: Footer to be displayed on the invoice.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , paymentLinksResourceInvoiceCreationInvoiceData'NonNullableFooter :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text))
  -- | issuer: The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
  , paymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable))
  -- | metadata: Set of [key-value pairs](https:\/\/stripe.com\/docs\/api\/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
  , paymentLinksResourceInvoiceCreationInvoiceData'NonNullableMetadata :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Aeson.Types.Internal.Object))
  -- | rendering_options: Options for invoice PDF rendering.
  , paymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account_tax_ids" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("custom_fields" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableCustomFields obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("description" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableDescription obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("footer" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableFooter obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("issuer" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("metadata" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableMetadata obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("rendering_options" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account_tax_ids" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("custom_fields" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableCustomFields obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("description" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableDescription obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("footer" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableFooter obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("issuer" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("metadata" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableMetadata obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("rendering_options" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable" (\obj -> ((((((GHC.Base.pure PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "account_tax_ids")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "custom_fields")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "description")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "footer")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "issuer")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "metadata")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "rendering_options"))}
-- | Create a new 'PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable' with all required fields.
mkPaymentLinksResourceInvoiceCreationInvoiceData'NonNullable :: PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable
mkPaymentLinksResourceInvoiceCreationInvoiceData'NonNullable = PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable{paymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds = GHC.Maybe.Nothing,
                                                                                                                          paymentLinksResourceInvoiceCreationInvoiceData'NonNullableCustomFields = GHC.Maybe.Nothing,
                                                                                                                          paymentLinksResourceInvoiceCreationInvoiceData'NonNullableDescription = GHC.Maybe.Nothing,
                                                                                                                          paymentLinksResourceInvoiceCreationInvoiceData'NonNullableFooter = GHC.Maybe.Nothing,
                                                                                                                          paymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer = GHC.Maybe.Nothing,
                                                                                                                          paymentLinksResourceInvoiceCreationInvoiceData'NonNullableMetadata = GHC.Maybe.Nothing,
                                                                                                                          paymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions = GHC.Maybe.Nothing}
-- | Defines the oneOf schema located at @components.schemas.payment_links_resource_invoice_creation.properties.invoice_data.anyOf.properties.account_tax_ids.items.anyOf@ in the specification.
-- 
-- 
data PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableVariants =
   PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableText Data.Text.Internal.Text
  | PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableTaxId TaxId
  | PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableDeletedTaxId DeletedTaxId
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableVariants
    where {toJSON (PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableText a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableTaxId a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableDeletedTaxId a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableVariants
    where {parseJSON val = case (PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableText Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableTaxId Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableDeletedTaxId Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched")) of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the object schema located at @components.schemas.payment_links_resource_invoice_creation.properties.invoice_data.anyOf.properties.issuer.anyOf@ in the specification.
-- 
-- The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
data PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable = PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable {
  -- | account: The connected account being referenced when \`type\` is \`account\`.
  paymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount :: (GHC.Maybe.Maybe PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount'Variants)
  -- | type: Type of the account referenced.
  , paymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType :: (GHC.Maybe.Maybe PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType')
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable" (\obj -> (GHC.Base.pure PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "account")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "type"))}
-- | Create a new 'PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable' with all required fields.
mkPaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable :: PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable
mkPaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable = PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable{paymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount = GHC.Maybe.Nothing,
                                                                                                                                                              paymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType = GHC.Maybe.Nothing}
-- | Defines the oneOf schema located at @components.schemas.payment_links_resource_invoice_creation.properties.invoice_data.anyOf.properties.issuer.anyOf.properties.account.anyOf@ in the specification.
-- 
-- The connected account being referenced when \`type\` is \`account\`.
data PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount'Variants =
   PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount'Text Data.Text.Internal.Text
  | PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount'Account Account
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount'Variants
    where {toJSON (PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount'Text a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount'Account a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount'Variants
    where {parseJSON val = case (PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount'Text Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount'Account Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the enum schema located at @components.schemas.payment_links_resource_invoice_creation.properties.invoice_data.anyOf.properties.issuer.anyOf.properties.type@ in the specification.
-- 
-- Type of the account referenced.
data PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType' =
   PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'EnumAccount -- ^ Represents the JSON value @"account"@
  | PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'EnumSelf -- ^ Represents the JSON value @"self"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'
    where {toJSON (PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'Other val) = val;
           toJSON (PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'EnumAccount) = "account";
           toJSON (PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'EnumSelf) = "self"}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "account" -> PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'EnumAccount
                                             | val GHC.Classes.== "self" -> PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'EnumSelf
                                             | GHC.Base.otherwise -> PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'Other val)}
-- | Defines the object schema located at @components.schemas.payment_links_resource_invoice_creation.properties.invoice_data.anyOf.properties.rendering_options.anyOf@ in the specification.
-- 
-- Options for invoice PDF rendering.
data PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable = PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable {
  -- | amount_tax_display: How line-item prices and amounts will be displayed with respect to tax on invoice PDFs.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  paymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullableAmountTaxDisplay :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("amount_tax_display" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullableAmountTaxDisplay obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("amount_tax_display" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullableAmountTaxDisplay obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable" (\obj -> GHC.Base.pure PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "amount_tax_display"))}
-- | Create a new 'PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable' with all required fields.
mkPaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable :: PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable
mkPaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable = PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable{paymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullableAmountTaxDisplay = GHC.Maybe.Nothing}
