module StripeAPI.Types.PaymentLinksResourceInvoiceSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceInvoiceSettings
instance Show PaymentLinksResourceInvoiceSettings
instance Eq PaymentLinksResourceInvoiceSettings
instance FromJSON PaymentLinksResourceInvoiceSettings
instance ToJSON PaymentLinksResourceInvoiceSettings
data PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Show PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Eq PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
instance FromJSON PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
instance ToJSON PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
data PaymentLinksResourceInvoiceSettingsIssuer'NonNullable
instance Show PaymentLinksResourceInvoiceSettingsIssuer'NonNullable
instance Eq PaymentLinksResourceInvoiceSettingsIssuer'NonNullable
instance FromJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullable
instance ToJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullable
data PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Variants
instance Show PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Variants
instance Eq PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Variants
instance FromJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Variants
instance ToJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Variants
data PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'
instance Show PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'
instance Eq PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'
instance FromJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'
instance ToJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'
data PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
instance Show PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
instance Eq PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
instance FromJSON PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
instance ToJSON PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
