-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema PaymentLinksResourceInvoiceSettings
module StripeAPI.Types.PaymentLinksResourceInvoiceSettings where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.Account
import {-# SOURCE #-} StripeAPI.Types.ConnectAccountReference
import {-# SOURCE #-} StripeAPI.Types.DeletedTaxId
import {-# SOURCE #-} StripeAPI.Types.InvoiceSettingCustomField
import {-# SOURCE #-} StripeAPI.Types.InvoiceSettingRenderingOptions
import {-# SOURCE #-} StripeAPI.Types.TaxId

-- | Defines the object schema located at @components.schemas.payment_links_resource_invoice_settings@ in the specification.
-- 
-- 
data PaymentLinksResourceInvoiceSettings = PaymentLinksResourceInvoiceSettings {
  -- | account_tax_ids: The account tax IDs associated with the invoice.
  paymentLinksResourceInvoiceSettingsAccountTaxIds :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable ([PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants])))
  -- | custom_fields: A list of up to 4 custom fields to be displayed on the invoice.
  , paymentLinksResourceInvoiceSettingsCustomFields :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable ([InvoiceSettingCustomField])))
  -- | description: An arbitrary string attached to the object. Often useful for displaying to users.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , paymentLinksResourceInvoiceSettingsDescription :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text))
  -- | footer: Footer to be displayed on the invoice.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , paymentLinksResourceInvoiceSettingsFooter :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text))
  -- | issuer: The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
  , paymentLinksResourceInvoiceSettingsIssuer :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable PaymentLinksResourceInvoiceSettingsIssuer'NonNullable))
  -- | metadata: Set of [key-value pairs](https:\/\/stripe.com\/docs\/api\/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
  , paymentLinksResourceInvoiceSettingsMetadata :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Aeson.Types.Internal.Object))
  -- | rendering_options: Options for invoice PDF rendering.
  , paymentLinksResourceInvoiceSettingsRenderingOptions :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentLinksResourceInvoiceSettings
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account_tax_ids" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsAccountTaxIds obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("custom_fields" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsCustomFields obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("description" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsDescription obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("footer" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsFooter obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("issuer" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsIssuer obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("metadata" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsMetadata obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("rendering_options" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsRenderingOptions obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account_tax_ids" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsAccountTaxIds obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("custom_fields" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsCustomFields obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("description" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsDescription obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("footer" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsFooter obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("issuer" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsIssuer obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("metadata" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsMetadata obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("rendering_options" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsRenderingOptions obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentLinksResourceInvoiceSettings
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentLinksResourceInvoiceSettings" (\obj -> ((((((GHC.Base.pure PaymentLinksResourceInvoiceSettings GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "account_tax_ids")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "custom_fields")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "description")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "footer")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "issuer")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "metadata")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "rendering_options"))}
-- | Create a new 'PaymentLinksResourceInvoiceSettings' with all required fields.
mkPaymentLinksResourceInvoiceSettings :: PaymentLinksResourceInvoiceSettings
mkPaymentLinksResourceInvoiceSettings = PaymentLinksResourceInvoiceSettings{paymentLinksResourceInvoiceSettingsAccountTaxIds = GHC.Maybe.Nothing,
                                                                            paymentLinksResourceInvoiceSettingsCustomFields = GHC.Maybe.Nothing,
                                                                            paymentLinksResourceInvoiceSettingsDescription = GHC.Maybe.Nothing,
                                                                            paymentLinksResourceInvoiceSettingsFooter = GHC.Maybe.Nothing,
                                                                            paymentLinksResourceInvoiceSettingsIssuer = GHC.Maybe.Nothing,
                                                                            paymentLinksResourceInvoiceSettingsMetadata = GHC.Maybe.Nothing,
                                                                            paymentLinksResourceInvoiceSettingsRenderingOptions = GHC.Maybe.Nothing}
-- | Defines the oneOf schema located at @components.schemas.payment_links_resource_invoice_settings.properties.account_tax_ids.items.anyOf@ in the specification.
-- 
-- 
data PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants =
   PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableText Data.Text.Internal.Text
  | PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableTaxId TaxId
  | PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableDeletedTaxId DeletedTaxId
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
    where {toJSON (PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableText a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableTaxId a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableDeletedTaxId a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
    where {parseJSON val = case (PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableText Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableTaxId Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableDeletedTaxId Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched")) of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the object schema located at @components.schemas.payment_links_resource_invoice_settings.properties.issuer.anyOf@ in the specification.
-- 
-- The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
data PaymentLinksResourceInvoiceSettingsIssuer'NonNullable = PaymentLinksResourceInvoiceSettingsIssuer'NonNullable {
  -- | account: The connected account being referenced when \`type\` is \`account\`.
  paymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount :: (GHC.Maybe.Maybe PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Variants)
  -- | type: Type of the account referenced.
  , paymentLinksResourceInvoiceSettingsIssuer'NonNullableType :: (GHC.Maybe.Maybe PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType')
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullable
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsIssuer'NonNullableType obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsIssuer'NonNullableType obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullable
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentLinksResourceInvoiceSettingsIssuer'NonNullable" (\obj -> (GHC.Base.pure PaymentLinksResourceInvoiceSettingsIssuer'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "account")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "type"))}
-- | Create a new 'PaymentLinksResourceInvoiceSettingsIssuer'NonNullable' with all required fields.
mkPaymentLinksResourceInvoiceSettingsIssuer'NonNullable :: PaymentLinksResourceInvoiceSettingsIssuer'NonNullable
mkPaymentLinksResourceInvoiceSettingsIssuer'NonNullable = PaymentLinksResourceInvoiceSettingsIssuer'NonNullable{paymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount = GHC.Maybe.Nothing,
                                                                                                                paymentLinksResourceInvoiceSettingsIssuer'NonNullableType = GHC.Maybe.Nothing}
-- | Defines the oneOf schema located at @components.schemas.payment_links_resource_invoice_settings.properties.issuer.anyOf.properties.account.anyOf@ in the specification.
-- 
-- The connected account being referenced when \`type\` is \`account\`.
data PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Variants =
   PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Text Data.Text.Internal.Text
  | PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Account Account
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Variants
    where {toJSON (PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Text a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Account a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Variants
    where {parseJSON val = case (PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Text Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Account Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the enum schema located at @components.schemas.payment_links_resource_invoice_settings.properties.issuer.anyOf.properties.type@ in the specification.
-- 
-- Type of the account referenced.
data PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType' =
   PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'EnumAccount -- ^ Represents the JSON value @"account"@
  | PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'EnumSelf -- ^ Represents the JSON value @"self"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'
    where {toJSON (PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'Other val) = val;
           toJSON (PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'EnumAccount) = "account";
           toJSON (PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'EnumSelf) = "self"}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "account" -> PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'EnumAccount
                                             | val GHC.Classes.== "self" -> PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'EnumSelf
                                             | GHC.Base.otherwise -> PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'Other val)}
-- | Defines the object schema located at @components.schemas.payment_links_resource_invoice_settings.properties.rendering_options.anyOf@ in the specification.
-- 
-- Options for invoice PDF rendering.
data PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable = PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable {
  -- | amount_tax_display: How line-item prices and amounts will be displayed with respect to tax on invoice PDFs.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  paymentLinksResourceInvoiceSettingsRenderingOptions'NonNullableAmountTaxDisplay :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("amount_tax_display" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsRenderingOptions'NonNullableAmountTaxDisplay obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("amount_tax_display" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceInvoiceSettingsRenderingOptions'NonNullableAmountTaxDisplay obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable" (\obj -> GHC.Base.pure PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "amount_tax_display"))}
-- | Create a new 'PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable' with all required fields.
mkPaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable :: PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
mkPaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable = PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable{paymentLinksResourceInvoiceSettingsRenderingOptions'NonNullableAmountTaxDisplay = GHC.Maybe.Nothing}
