-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema SchedulesPhaseAutomaticTax
module StripeAPI.Types.SchedulesPhaseAutomaticTax where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.Account
import {-# SOURCE #-} StripeAPI.Types.ConnectAccountReference

-- | Defines the object schema located at @components.schemas.schedules_phase_automatic_tax@ in the specification.
-- 
-- 
data SchedulesPhaseAutomaticTax = SchedulesPhaseAutomaticTax {
  -- | enabled: Whether Stripe automatically computes tax on invoices created during this phase.
  schedulesPhaseAutomaticTaxEnabled :: GHC.Types.Bool
  -- | liability: The account that\'s liable for tax. If set, the business address and tax registrations required to perform the tax calculation are loaded from this account. The tax transaction is returned in the report of the connected account.
  , schedulesPhaseAutomaticTaxLiability :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable SchedulesPhaseAutomaticTaxLiability'NonNullable))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON SchedulesPhaseAutomaticTax
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["enabled" Data.Aeson.Types.ToJSON..= schedulesPhaseAutomaticTaxEnabled obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("liability" Data.Aeson.Types.ToJSON..=)) (schedulesPhaseAutomaticTaxLiability obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["enabled" Data.Aeson.Types.ToJSON..= schedulesPhaseAutomaticTaxEnabled obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("liability" Data.Aeson.Types.ToJSON..=)) (schedulesPhaseAutomaticTaxLiability obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON SchedulesPhaseAutomaticTax
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "SchedulesPhaseAutomaticTax" (\obj -> (GHC.Base.pure SchedulesPhaseAutomaticTax GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "enabled")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "liability"))}
-- | Create a new 'SchedulesPhaseAutomaticTax' with all required fields.
mkSchedulesPhaseAutomaticTax :: GHC.Types.Bool -- ^ 'schedulesPhaseAutomaticTaxEnabled'
  -> SchedulesPhaseAutomaticTax
mkSchedulesPhaseAutomaticTax schedulesPhaseAutomaticTaxEnabled = SchedulesPhaseAutomaticTax{schedulesPhaseAutomaticTaxEnabled = schedulesPhaseAutomaticTaxEnabled,
                                                                                            schedulesPhaseAutomaticTaxLiability = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.schedules_phase_automatic_tax.properties.liability.anyOf@ in the specification.
-- 
-- The account that\\\'s liable for tax. If set, the business address and tax registrations required to perform the tax calculation are loaded from this account. The tax transaction is returned in the report of the connected account.
data SchedulesPhaseAutomaticTaxLiability'NonNullable = SchedulesPhaseAutomaticTaxLiability'NonNullable {
  -- | account: The connected account being referenced when \`type\` is \`account\`.
  schedulesPhaseAutomaticTaxLiability'NonNullableAccount :: (GHC.Maybe.Maybe SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Variants)
  -- | type: Type of the account referenced.
  , schedulesPhaseAutomaticTaxLiability'NonNullableType :: (GHC.Maybe.Maybe SchedulesPhaseAutomaticTaxLiability'NonNullableType')
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON SchedulesPhaseAutomaticTaxLiability'NonNullable
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account" Data.Aeson.Types.ToJSON..=)) (schedulesPhaseAutomaticTaxLiability'NonNullableAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (schedulesPhaseAutomaticTaxLiability'NonNullableType obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account" Data.Aeson.Types.ToJSON..=)) (schedulesPhaseAutomaticTaxLiability'NonNullableAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (schedulesPhaseAutomaticTaxLiability'NonNullableType obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON SchedulesPhaseAutomaticTaxLiability'NonNullable
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "SchedulesPhaseAutomaticTaxLiability'NonNullable" (\obj -> (GHC.Base.pure SchedulesPhaseAutomaticTaxLiability'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "account")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "type"))}
-- | Create a new 'SchedulesPhaseAutomaticTaxLiability'NonNullable' with all required fields.
mkSchedulesPhaseAutomaticTaxLiability'NonNullable :: SchedulesPhaseAutomaticTaxLiability'NonNullable
mkSchedulesPhaseAutomaticTaxLiability'NonNullable = SchedulesPhaseAutomaticTaxLiability'NonNullable{schedulesPhaseAutomaticTaxLiability'NonNullableAccount = GHC.Maybe.Nothing,
                                                                                                    schedulesPhaseAutomaticTaxLiability'NonNullableType = GHC.Maybe.Nothing}
-- | Defines the oneOf schema located at @components.schemas.schedules_phase_automatic_tax.properties.liability.anyOf.properties.account.anyOf@ in the specification.
-- 
-- The connected account being referenced when \`type\` is \`account\`.
data SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Variants =
   SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Text Data.Text.Internal.Text
  | SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Account Account
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Variants
    where {toJSON (SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Text a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Account a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Variants
    where {parseJSON val = case (SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Text Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Account Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the enum schema located at @components.schemas.schedules_phase_automatic_tax.properties.liability.anyOf.properties.type@ in the specification.
-- 
-- Type of the account referenced.
data SchedulesPhaseAutomaticTaxLiability'NonNullableType' =
   SchedulesPhaseAutomaticTaxLiability'NonNullableType'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | SchedulesPhaseAutomaticTaxLiability'NonNullableType'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | SchedulesPhaseAutomaticTaxLiability'NonNullableType'EnumAccount -- ^ Represents the JSON value @"account"@
  | SchedulesPhaseAutomaticTaxLiability'NonNullableType'EnumSelf -- ^ Represents the JSON value @"self"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON SchedulesPhaseAutomaticTaxLiability'NonNullableType'
    where {toJSON (SchedulesPhaseAutomaticTaxLiability'NonNullableType'Other val) = val;
           toJSON (SchedulesPhaseAutomaticTaxLiability'NonNullableType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (SchedulesPhaseAutomaticTaxLiability'NonNullableType'EnumAccount) = "account";
           toJSON (SchedulesPhaseAutomaticTaxLiability'NonNullableType'EnumSelf) = "self"}
instance Data.Aeson.Types.FromJSON.FromJSON SchedulesPhaseAutomaticTaxLiability'NonNullableType'
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "account" -> SchedulesPhaseAutomaticTaxLiability'NonNullableType'EnumAccount
                                             | val GHC.Classes.== "self" -> SchedulesPhaseAutomaticTaxLiability'NonNullableType'EnumSelf
                                             | GHC.Base.otherwise -> SchedulesPhaseAutomaticTaxLiability'NonNullableType'Other val)}
