module StripeAPI.Types.SubscriptionAutomaticTax where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SubscriptionAutomaticTax
instance Show SubscriptionAutomaticTax
instance Eq SubscriptionAutomaticTax
instance FromJSON SubscriptionAutomaticTax
instance ToJSON SubscriptionAutomaticTax
data SubscriptionAutomaticTaxLiability'NonNullable
instance Show SubscriptionAutomaticTaxLiability'NonNullable
instance Eq SubscriptionAutomaticTaxLiability'NonNullable
instance FromJSON SubscriptionAutomaticTaxLiability'NonNullable
instance ToJSON SubscriptionAutomaticTaxLiability'NonNullable
data SubscriptionAutomaticTaxLiability'NonNullableAccount'Variants
instance Show SubscriptionAutomaticTaxLiability'NonNullableAccount'Variants
instance Eq SubscriptionAutomaticTaxLiability'NonNullableAccount'Variants
instance FromJSON SubscriptionAutomaticTaxLiability'NonNullableAccount'Variants
instance ToJSON SubscriptionAutomaticTaxLiability'NonNullableAccount'Variants
data SubscriptionAutomaticTaxLiability'NonNullableType'
instance Show SubscriptionAutomaticTaxLiability'NonNullableType'
instance Eq SubscriptionAutomaticTaxLiability'NonNullableType'
instance FromJSON SubscriptionAutomaticTaxLiability'NonNullableType'
instance ToJSON SubscriptionAutomaticTaxLiability'NonNullableType'
