module StripeAPI.Types.CustomerSessionResourceComponentsResourceBuyButton where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CustomerSessionResourceComponentsResourceBuyButton
instance Show CustomerSessionResourceComponentsResourceBuyButton
instance Eq CustomerSessionResourceComponentsResourceBuyButton
instance FromJSON CustomerSessionResourceComponentsResourceBuyButton
instance ToJSON CustomerSessionResourceComponentsResourceBuyButton
