module StripeAPI.Types.CustomerSessionResourceComponents where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CustomerSessionResourceComponents
instance Show CustomerSessionResourceComponents
instance Eq CustomerSessionResourceComponents
instance FromJSON CustomerSessionResourceComponents
instance ToJSON CustomerSessionResourceComponents
