-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema InvoiceSettingQuoteSetting
module StripeAPI.Types.InvoiceSettingQuoteSetting where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.ConnectAccountReference

-- | Defines the object schema located at @components.schemas.invoice_setting_quote_setting@ in the specification.
-- 
-- 
data InvoiceSettingQuoteSetting = InvoiceSettingQuoteSetting {
  -- | days_until_due: Number of days within which a customer must pay invoices generated by this quote. This value will be \`null\` for quotes where \`collection_method=charge_automatically\`.
  invoiceSettingQuoteSettingDaysUntilDue :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable GHC.Types.Int))
  -- | issuer: 
  , invoiceSettingQuoteSettingIssuer :: ConnectAccountReference
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON InvoiceSettingQuoteSetting
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("days_until_due" Data.Aeson.Types.ToJSON..=)) (invoiceSettingQuoteSettingDaysUntilDue obj) : ["issuer" Data.Aeson.Types.ToJSON..= invoiceSettingQuoteSettingIssuer obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("days_until_due" Data.Aeson.Types.ToJSON..=)) (invoiceSettingQuoteSettingDaysUntilDue obj) : ["issuer" Data.Aeson.Types.ToJSON..= invoiceSettingQuoteSettingIssuer obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON InvoiceSettingQuoteSetting
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "InvoiceSettingQuoteSetting" (\obj -> (GHC.Base.pure InvoiceSettingQuoteSetting GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "days_until_due")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "issuer"))}
-- | Create a new 'InvoiceSettingQuoteSetting' with all required fields.
mkInvoiceSettingQuoteSetting :: ConnectAccountReference -- ^ 'invoiceSettingQuoteSettingIssuer'
  -> InvoiceSettingQuoteSetting
mkInvoiceSettingQuoteSetting invoiceSettingQuoteSettingIssuer = InvoiceSettingQuoteSetting{invoiceSettingQuoteSettingDaysUntilDue = GHC.Maybe.Nothing,
                                                                                           invoiceSettingQuoteSettingIssuer = invoiceSettingQuoteSettingIssuer}
