-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema PaymentPagesCheckoutSessionInvoiceSettings
module StripeAPI.Types.PaymentPagesCheckoutSessionInvoiceSettings where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.Account
import {-# SOURCE #-} StripeAPI.Types.ConnectAccountReference
import {-# SOURCE #-} StripeAPI.Types.DeletedTaxId
import {-# SOURCE #-} StripeAPI.Types.InvoiceSettingCustomField
import {-# SOURCE #-} StripeAPI.Types.InvoiceSettingRenderingOptions
import {-# SOURCE #-} StripeAPI.Types.TaxId

-- | Defines the object schema located at @components.schemas.payment_pages_checkout_session_invoice_settings@ in the specification.
-- 
-- 
data PaymentPagesCheckoutSessionInvoiceSettings = PaymentPagesCheckoutSessionInvoiceSettings {
  -- | account_tax_ids: The account tax IDs associated with the invoice.
  paymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable ([PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants])))
  -- | custom_fields: Custom fields displayed on the invoice.
  , paymentPagesCheckoutSessionInvoiceSettingsCustomFields :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable ([InvoiceSettingCustomField])))
  -- | description: An arbitrary string attached to the object. Often useful for displaying to users.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , paymentPagesCheckoutSessionInvoiceSettingsDescription :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text))
  -- | footer: Footer displayed on the invoice.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , paymentPagesCheckoutSessionInvoiceSettingsFooter :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text))
  -- | issuer: The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
  , paymentPagesCheckoutSessionInvoiceSettingsIssuer :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable))
  -- | metadata: Set of [key-value pairs](https:\/\/stripe.com\/docs\/api\/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
  , paymentPagesCheckoutSessionInvoiceSettingsMetadata :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Aeson.Types.Internal.Object))
  -- | rendering_options: Options for invoice PDF rendering.
  , paymentPagesCheckoutSessionInvoiceSettingsRenderingOptions :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentPagesCheckoutSessionInvoiceSettings
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account_tax_ids" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("custom_fields" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsCustomFields obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("description" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsDescription obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("footer" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsFooter obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("issuer" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsIssuer obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("metadata" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsMetadata obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("rendering_options" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsRenderingOptions obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account_tax_ids" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("custom_fields" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsCustomFields obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("description" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsDescription obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("footer" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsFooter obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("issuer" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsIssuer obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("metadata" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsMetadata obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("rendering_options" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsRenderingOptions obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentPagesCheckoutSessionInvoiceSettings
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentPagesCheckoutSessionInvoiceSettings" (\obj -> ((((((GHC.Base.pure PaymentPagesCheckoutSessionInvoiceSettings GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "account_tax_ids")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "custom_fields")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "description")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "footer")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "issuer")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "metadata")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "rendering_options"))}
-- | Create a new 'PaymentPagesCheckoutSessionInvoiceSettings' with all required fields.
mkPaymentPagesCheckoutSessionInvoiceSettings :: PaymentPagesCheckoutSessionInvoiceSettings
mkPaymentPagesCheckoutSessionInvoiceSettings = PaymentPagesCheckoutSessionInvoiceSettings{paymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds = GHC.Maybe.Nothing,
                                                                                          paymentPagesCheckoutSessionInvoiceSettingsCustomFields = GHC.Maybe.Nothing,
                                                                                          paymentPagesCheckoutSessionInvoiceSettingsDescription = GHC.Maybe.Nothing,
                                                                                          paymentPagesCheckoutSessionInvoiceSettingsFooter = GHC.Maybe.Nothing,
                                                                                          paymentPagesCheckoutSessionInvoiceSettingsIssuer = GHC.Maybe.Nothing,
                                                                                          paymentPagesCheckoutSessionInvoiceSettingsMetadata = GHC.Maybe.Nothing,
                                                                                          paymentPagesCheckoutSessionInvoiceSettingsRenderingOptions = GHC.Maybe.Nothing}
-- | Defines the oneOf schema located at @components.schemas.payment_pages_checkout_session_invoice_settings.properties.account_tax_ids.items.anyOf@ in the specification.
-- 
-- 
data PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants =
   PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableText Data.Text.Internal.Text
  | PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableTaxId TaxId
  | PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableDeletedTaxId DeletedTaxId
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
    where {toJSON (PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableText a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableTaxId a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableDeletedTaxId a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
    where {parseJSON val = case (PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableText Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableTaxId Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableDeletedTaxId Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched")) of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the object schema located at @components.schemas.payment_pages_checkout_session_invoice_settings.properties.issuer.anyOf@ in the specification.
-- 
-- The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
data PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable = PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable {
  -- | account: The connected account being referenced when \`type\` is \`account\`.
  paymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount :: (GHC.Maybe.Maybe PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Variants)
  -- | type: Type of the account referenced.
  , paymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType :: (GHC.Maybe.Maybe PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType')
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable" (\obj -> (GHC.Base.pure PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "account")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "type"))}
-- | Create a new 'PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable' with all required fields.
mkPaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable :: PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable
mkPaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable = PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable{paymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount = GHC.Maybe.Nothing,
                                                                                                                              paymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType = GHC.Maybe.Nothing}
-- | Defines the oneOf schema located at @components.schemas.payment_pages_checkout_session_invoice_settings.properties.issuer.anyOf.properties.account.anyOf@ in the specification.
-- 
-- The connected account being referenced when \`type\` is \`account\`.
data PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Variants =
   PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Text Data.Text.Internal.Text
  | PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Account Account
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Variants
    where {toJSON (PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Text a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Account a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Variants
    where {parseJSON val = case (PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Text Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Account Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the enum schema located at @components.schemas.payment_pages_checkout_session_invoice_settings.properties.issuer.anyOf.properties.type@ in the specification.
-- 
-- Type of the account referenced.
data PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType' =
   PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'EnumAccount -- ^ Represents the JSON value @"account"@
  | PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'EnumSelf -- ^ Represents the JSON value @"self"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'
    where {toJSON (PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'Other val) = val;
           toJSON (PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'EnumAccount) = "account";
           toJSON (PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'EnumSelf) = "self"}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "account" -> PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'EnumAccount
                                             | val GHC.Classes.== "self" -> PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'EnumSelf
                                             | GHC.Base.otherwise -> PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'Other val)}
-- | Defines the object schema located at @components.schemas.payment_pages_checkout_session_invoice_settings.properties.rendering_options.anyOf@ in the specification.
-- 
-- Options for invoice PDF rendering.
data PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable = PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable {
  -- | amount_tax_display: How line-item prices and amounts will be displayed with respect to tax on invoice PDFs.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  paymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullableAmountTaxDisplay :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("amount_tax_display" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullableAmountTaxDisplay obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("amount_tax_display" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullableAmountTaxDisplay obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable" (\obj -> GHC.Base.pure PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "amount_tax_display"))}
-- | Create a new 'PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable' with all required fields.
mkPaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable :: PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
mkPaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable = PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable{paymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullableAmountTaxDisplay = GHC.Maybe.Nothing}
