module StripeAPI.Types.PaymentPagesCheckoutSessionAutomaticTax where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionAutomaticTax
instance Show PaymentPagesCheckoutSessionAutomaticTax
instance Eq PaymentPagesCheckoutSessionAutomaticTax
instance FromJSON PaymentPagesCheckoutSessionAutomaticTax
instance ToJSON PaymentPagesCheckoutSessionAutomaticTax
data PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullable
instance Show PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullable
instance Eq PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullable
instance FromJSON PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullable
instance ToJSON PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullable
data PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableAccount'Variants
instance Show PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableAccount'Variants
instance Eq PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableAccount'Variants
instance FromJSON PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableAccount'Variants
instance ToJSON PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableAccount'Variants
data PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableType'
instance Show PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableType'
instance Eq PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableType'
instance FromJSON PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableType'
instance ToJSON PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableType'
data PaymentPagesCheckoutSessionAutomaticTaxStatus'NonNullable
instance Show PaymentPagesCheckoutSessionAutomaticTaxStatus'NonNullable
instance Eq PaymentPagesCheckoutSessionAutomaticTaxStatus'NonNullable
instance FromJSON PaymentPagesCheckoutSessionAutomaticTaxStatus'NonNullable
instance ToJSON PaymentPagesCheckoutSessionAutomaticTaxStatus'NonNullable
