module StripeAPI.Types.PaymentPagesCheckoutSessionInvoiceSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionInvoiceSettings
instance Show PaymentPagesCheckoutSessionInvoiceSettings
instance Eq PaymentPagesCheckoutSessionInvoiceSettings
instance FromJSON PaymentPagesCheckoutSessionInvoiceSettings
instance ToJSON PaymentPagesCheckoutSessionInvoiceSettings
data PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Show PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Eq PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance FromJSON PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance ToJSON PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
data PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable
instance Show PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable
instance Eq PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable
instance FromJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable
instance ToJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable
data PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Variants
instance Show PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Variants
instance Eq PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Variants
instance FromJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Variants
instance ToJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Variants
data PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'
instance Show PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'
instance Eq PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'
instance FromJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'
instance ToJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'
data PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
instance Show PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
instance Eq PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
instance FromJSON PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
instance ToJSON PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
