module StripeAPI.Types.PaymentLinksResourceAutomaticTax where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceAutomaticTax
instance Show PaymentLinksResourceAutomaticTax
instance Eq PaymentLinksResourceAutomaticTax
instance FromJSON PaymentLinksResourceAutomaticTax
instance ToJSON PaymentLinksResourceAutomaticTax
data PaymentLinksResourceAutomaticTaxLiability'NonNullable
instance Show PaymentLinksResourceAutomaticTaxLiability'NonNullable
instance Eq PaymentLinksResourceAutomaticTaxLiability'NonNullable
instance FromJSON PaymentLinksResourceAutomaticTaxLiability'NonNullable
instance ToJSON PaymentLinksResourceAutomaticTaxLiability'NonNullable
data PaymentLinksResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance Show PaymentLinksResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance Eq PaymentLinksResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance FromJSON PaymentLinksResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance ToJSON PaymentLinksResourceAutomaticTaxLiability'NonNullableAccount'Variants
data PaymentLinksResourceAutomaticTaxLiability'NonNullableType'
instance Show PaymentLinksResourceAutomaticTaxLiability'NonNullableType'
instance Eq PaymentLinksResourceAutomaticTaxLiability'NonNullableType'
instance FromJSON PaymentLinksResourceAutomaticTaxLiability'NonNullableType'
instance ToJSON PaymentLinksResourceAutomaticTaxLiability'NonNullableType'
