module StripeAPI.Types.QuotesResourceAutomaticTax where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data QuotesResourceAutomaticTax
instance Show QuotesResourceAutomaticTax
instance Eq QuotesResourceAutomaticTax
instance FromJSON QuotesResourceAutomaticTax
instance ToJSON QuotesResourceAutomaticTax
data QuotesResourceAutomaticTaxLiability'NonNullable
instance Show QuotesResourceAutomaticTaxLiability'NonNullable
instance Eq QuotesResourceAutomaticTaxLiability'NonNullable
instance FromJSON QuotesResourceAutomaticTaxLiability'NonNullable
instance ToJSON QuotesResourceAutomaticTaxLiability'NonNullable
data QuotesResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance Show QuotesResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance Eq QuotesResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance FromJSON QuotesResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance ToJSON QuotesResourceAutomaticTaxLiability'NonNullableAccount'Variants
data QuotesResourceAutomaticTaxLiability'NonNullableType'
instance Show QuotesResourceAutomaticTaxLiability'NonNullableType'
instance Eq QuotesResourceAutomaticTaxLiability'NonNullableType'
instance FromJSON QuotesResourceAutomaticTaxLiability'NonNullableType'
instance ToJSON QuotesResourceAutomaticTaxLiability'NonNullableType'
data QuotesResourceAutomaticTaxStatus'NonNullable
instance Show QuotesResourceAutomaticTaxStatus'NonNullable
instance Eq QuotesResourceAutomaticTaxStatus'NonNullable
instance FromJSON QuotesResourceAutomaticTaxStatus'NonNullable
instance ToJSON QuotesResourceAutomaticTaxStatus'NonNullable
