module StripeAPI.Types.SchedulesPhaseAutomaticTax where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SchedulesPhaseAutomaticTax
instance Show SchedulesPhaseAutomaticTax
instance Eq SchedulesPhaseAutomaticTax
instance FromJSON SchedulesPhaseAutomaticTax
instance ToJSON SchedulesPhaseAutomaticTax
data SchedulesPhaseAutomaticTaxLiability'NonNullable
instance Show SchedulesPhaseAutomaticTaxLiability'NonNullable
instance Eq SchedulesPhaseAutomaticTaxLiability'NonNullable
instance FromJSON SchedulesPhaseAutomaticTaxLiability'NonNullable
instance ToJSON SchedulesPhaseAutomaticTaxLiability'NonNullable
data SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Variants
instance Show SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Variants
instance Eq SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Variants
instance FromJSON SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Variants
instance ToJSON SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Variants
data SchedulesPhaseAutomaticTaxLiability'NonNullableType'
instance Show SchedulesPhaseAutomaticTaxLiability'NonNullableType'
instance Eq SchedulesPhaseAutomaticTaxLiability'NonNullableType'
instance FromJSON SchedulesPhaseAutomaticTaxLiability'NonNullableType'
instance ToJSON SchedulesPhaseAutomaticTaxLiability'NonNullableType'
