-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema SubscriptionAutomaticTax
module StripeAPI.Types.SubscriptionAutomaticTax where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.Account
import {-# SOURCE #-} StripeAPI.Types.ConnectAccountReference

-- | Defines the object schema located at @components.schemas.subscription_automatic_tax@ in the specification.
-- 
-- 
data SubscriptionAutomaticTax = SubscriptionAutomaticTax {
  -- | enabled: Whether Stripe automatically computes tax on this subscription.
  subscriptionAutomaticTaxEnabled :: GHC.Types.Bool
  -- | liability: The account that\'s liable for tax. If set, the business address and tax registrations required to perform the tax calculation are loaded from this account. The tax transaction is returned in the report of the connected account.
  , subscriptionAutomaticTaxLiability :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable SubscriptionAutomaticTaxLiability'NonNullable))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON SubscriptionAutomaticTax
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["enabled" Data.Aeson.Types.ToJSON..= subscriptionAutomaticTaxEnabled obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("liability" Data.Aeson.Types.ToJSON..=)) (subscriptionAutomaticTaxLiability obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["enabled" Data.Aeson.Types.ToJSON..= subscriptionAutomaticTaxEnabled obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("liability" Data.Aeson.Types.ToJSON..=)) (subscriptionAutomaticTaxLiability obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON SubscriptionAutomaticTax
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "SubscriptionAutomaticTax" (\obj -> (GHC.Base.pure SubscriptionAutomaticTax GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "enabled")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "liability"))}
-- | Create a new 'SubscriptionAutomaticTax' with all required fields.
mkSubscriptionAutomaticTax :: GHC.Types.Bool -- ^ 'subscriptionAutomaticTaxEnabled'
  -> SubscriptionAutomaticTax
mkSubscriptionAutomaticTax subscriptionAutomaticTaxEnabled = SubscriptionAutomaticTax{subscriptionAutomaticTaxEnabled = subscriptionAutomaticTaxEnabled,
                                                                                      subscriptionAutomaticTaxLiability = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.subscription_automatic_tax.properties.liability.anyOf@ in the specification.
-- 
-- The account that\\\'s liable for tax. If set, the business address and tax registrations required to perform the tax calculation are loaded from this account. The tax transaction is returned in the report of the connected account.
data SubscriptionAutomaticTaxLiability'NonNullable = SubscriptionAutomaticTaxLiability'NonNullable {
  -- | account: The connected account being referenced when \`type\` is \`account\`.
  subscriptionAutomaticTaxLiability'NonNullableAccount :: (GHC.Maybe.Maybe SubscriptionAutomaticTaxLiability'NonNullableAccount'Variants)
  -- | type: Type of the account referenced.
  , subscriptionAutomaticTaxLiability'NonNullableType :: (GHC.Maybe.Maybe SubscriptionAutomaticTaxLiability'NonNullableType')
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON SubscriptionAutomaticTaxLiability'NonNullable
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account" Data.Aeson.Types.ToJSON..=)) (subscriptionAutomaticTaxLiability'NonNullableAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (subscriptionAutomaticTaxLiability'NonNullableType obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account" Data.Aeson.Types.ToJSON..=)) (subscriptionAutomaticTaxLiability'NonNullableAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (subscriptionAutomaticTaxLiability'NonNullableType obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON SubscriptionAutomaticTaxLiability'NonNullable
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "SubscriptionAutomaticTaxLiability'NonNullable" (\obj -> (GHC.Base.pure SubscriptionAutomaticTaxLiability'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "account")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "type"))}
-- | Create a new 'SubscriptionAutomaticTaxLiability'NonNullable' with all required fields.
mkSubscriptionAutomaticTaxLiability'NonNullable :: SubscriptionAutomaticTaxLiability'NonNullable
mkSubscriptionAutomaticTaxLiability'NonNullable = SubscriptionAutomaticTaxLiability'NonNullable{subscriptionAutomaticTaxLiability'NonNullableAccount = GHC.Maybe.Nothing,
                                                                                                subscriptionAutomaticTaxLiability'NonNullableType = GHC.Maybe.Nothing}
-- | Defines the oneOf schema located at @components.schemas.subscription_automatic_tax.properties.liability.anyOf.properties.account.anyOf@ in the specification.
-- 
-- The connected account being referenced when \`type\` is \`account\`.
data SubscriptionAutomaticTaxLiability'NonNullableAccount'Variants =
   SubscriptionAutomaticTaxLiability'NonNullableAccount'Text Data.Text.Internal.Text
  | SubscriptionAutomaticTaxLiability'NonNullableAccount'Account Account
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON SubscriptionAutomaticTaxLiability'NonNullableAccount'Variants
    where {toJSON (SubscriptionAutomaticTaxLiability'NonNullableAccount'Text a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (SubscriptionAutomaticTaxLiability'NonNullableAccount'Account a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON SubscriptionAutomaticTaxLiability'NonNullableAccount'Variants
    where {parseJSON val = case (SubscriptionAutomaticTaxLiability'NonNullableAccount'Text Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((SubscriptionAutomaticTaxLiability'NonNullableAccount'Account Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the enum schema located at @components.schemas.subscription_automatic_tax.properties.liability.anyOf.properties.type@ in the specification.
-- 
-- Type of the account referenced.
data SubscriptionAutomaticTaxLiability'NonNullableType' =
   SubscriptionAutomaticTaxLiability'NonNullableType'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | SubscriptionAutomaticTaxLiability'NonNullableType'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | SubscriptionAutomaticTaxLiability'NonNullableType'EnumAccount -- ^ Represents the JSON value @"account"@
  | SubscriptionAutomaticTaxLiability'NonNullableType'EnumSelf -- ^ Represents the JSON value @"self"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON SubscriptionAutomaticTaxLiability'NonNullableType'
    where {toJSON (SubscriptionAutomaticTaxLiability'NonNullableType'Other val) = val;
           toJSON (SubscriptionAutomaticTaxLiability'NonNullableType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (SubscriptionAutomaticTaxLiability'NonNullableType'EnumAccount) = "account";
           toJSON (SubscriptionAutomaticTaxLiability'NonNullableType'EnumSelf) = "self"}
instance Data.Aeson.Types.FromJSON.FromJSON SubscriptionAutomaticTaxLiability'NonNullableType'
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "account" -> SubscriptionAutomaticTaxLiability'NonNullableType'EnumAccount
                                             | val GHC.Classes.== "self" -> SubscriptionAutomaticTaxLiability'NonNullableType'EnumSelf
                                             | GHC.Base.otherwise -> SubscriptionAutomaticTaxLiability'NonNullableType'Other val)}
