module StripeAPI.Types.SubscriptionSchedulesResourceDefaultSettingsAutomaticTax where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SubscriptionSchedulesResourceDefaultSettingsAutomaticTax
instance Show SubscriptionSchedulesResourceDefaultSettingsAutomaticTax
instance Eq SubscriptionSchedulesResourceDefaultSettingsAutomaticTax
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTax
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTax
data SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullable
instance Show SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullable
instance Eq SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullable
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullable
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullable
data SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableAccount'Variants
instance Show SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableAccount'Variants
instance Eq SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableAccount'Variants
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableAccount'Variants
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableAccount'Variants
data SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableType'
instance Show SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableType'
instance Eq SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableType'
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableType'
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableType'
